## Aufgabe 4 (Typ C)
a)
Erstellen Sie mit einem Editor eine txt-Datei mit einem kleinen Gedicht o.ä. Speichern Sie diese Datei
z.B. in einem Ordner tmp im Laufwerk C:.
I. Lesen sie den Dateiinhalt in Ihrem Python-Programm in eine Variable ein und geben Sie den    
Inhalt der Variable am Bildschirm aus.
II. Überprüfen Sie, ob am Ende ihres Programms die Datei geschlossen ist  

In [1]:
import numpy as np 
import pandas as pd
print('a1')
gedicht=open('Gedicht.txt',mode='r') #Die Txt wird mit der Openfunktion geöffnet, ein Argument ist der Zugriffszeiger als String, das andere ist der Zugriffsmodus. r steht für read. Dies wird der Variable gedicht zugewiesen.
print(gedicht.read())#die read Methode gibt den Text aus, der Text kann aber nicht bearbeitete werden.
gedicht.close()#der Zugriffszeiger wird mit der close Methode geschlossen.
print(gedicht.closed)#Kontrolle ob der Zugriffszeiger zu ist. TRUE FALSE als Antwort. closed ist ein Attribut.

a1
Gedicht:

Ich sahe mit betrachtendem Gemuete
juengst einen Kirschbaum, welcher bluehte,
In kuehler Nacht beim Mondenschein;
Ich glaubt, es koenne nichts von groesserer Weisse sein.
Es schien, ob waer ein Schnee gefallen.
Ein jeder, auch der kleinste Ast
Trug gleichsam eine rechte Last
Von zierlich-weissen runden Ballen.
Es ist kein Schwan so weiss, da naemlich jedes Blatt,
Indem daselbst des Mondes sanftes Licht
Selbst durch die zarten Blaetter bricht,
Sogar den Schatten weiss und sonder Schwaerze hat.
Unmoeglich, dacht ich, kann auf Erden
Was Weissers ausgefunden werden.
Indem ich nun bald hin, bald her
Im Schatten dieses Baumes gehe,
Sah ich von ungefaehr
Durch alle Blumen in die Hoehe
Und ward noch einen weissern Schein,
Der tausenmal so weiss, der tausendmal so klar,
Fast halb darob erstaunt, gewahr.
Der Bluete Schnee schien schwarz zu sein
Bei diesem weissen Glanz. Es fiel mir ins Gesicht
Von einem hellen Stern ein weisses Licht,
Das mir recht in die Seele strahlte.

Wie sehr i

# b)
I. Lesen Sie alle numerischen Daten ihrer Datei1 (also ohne die Spaltenbezeichner) in ein
Numpy-Array ein und geben Sie dieses am Bildschirm aus.    
II. Lesen Sie jetzt nur die numerischen Daten der ersten und dritten Spalte ihrer Datei in ein
Numpy-Array ein und geben Sie dieses am Bildschirm aus.    
III. Erzeugen Sie ein DataFrame datafr1 durch Einlesen der csv-Datei1 und wandeln Sie dieses
DataFrame in ein Numpy-Array um. Geben Sie dieses Numpy-Array am Bildschirm aus.    
IV. Erzeugen Sie ein DataFrame datafr2 durch Einlesen der csv-Datei2, wobei die erste Spalte
(ID) zur Indexspalte werden soll. Geben Sie mit Hilfe der Methode head() die ersten 5
Datensätze plus Überschriften dieses DataFrames am Bildschirm aus

In [2]:
#I)
RR='C:/tmp/Werte.csv' #Der Variable RR wird der Pfad der csv Datei zugewiesen

ausgabe1=np.loadtxt(RR,delimiter=',',skiprows=1)#die Numpymethode loadtxt übergibt als Argumente den Filename, wie die Werte in der Datei getrennt sind und skiprow gibt an wie viele Spalten übersprungen werden.
print(ausgabe1)


[[170.  60. 130.]
 [180.  87. 140.]
 [190.  89. 120.]
 [150.  50. 132.]
 [165.  56. 126.]
 [171.  53. 119.]]


In [9]:
#II)
ausgabe2=np.loadtxt(RR,delimiter=',',usecols=[0,2],skiprows=1)#das usecols Argument kann angeben welche Spalten angezeigt werden sollen. Die Spaltenangabe wird in eckige Klammern geschrieben und es wird von 0 gezählt (ähnlich wie beim Index).
print(ausgabe2)

[[170. 130.]
 [180. 140.]
 [190. 120.]
 [150. 132.]
 [165. 126.]
 [171. 119.]]


In [12]:
#III)
Werte=pd.read_csv(RR) #das Ergebnis der  read_csv Methode wir in der Variable Werte gespeichert. Die Methode ist aus dem Package pandas. Als Argument wird der filename übergeben.
Werte_array=Werte.values #die Werte werden als Array gespeichert. Neue Variable, values ist ein Attribut 
print(Werte_array) 


[[170  60 130]
 [180  87 140]
 [190  89 120]
 [150  50 132]
 [165  56 126]
 [171  53 119]]


pandas.core.frame.DataFrame

In [11]:
#IV)
RR_ID='C:/tmp/WerteID.csv' #zweite CSV Datei 
WerteID=pd.read_csv(RR_ID,index_col=0) #Index für Spalte 0 (1.Spalte) wird festgelegt. 
print(WerteID)


      Groesse   Gewicht   Systole
ID                               
PatA      170        60       130
PatB      180        87       140
PatC      190        89       120
PatD      150        50       132
PatE      165        56       126
PatF      171        53       119


pandas.core.frame.DataFrame

# c)
I. Geben Sie die Daten des ersten Arbeitsblattes (unabhängig vom Bezeichner des
Arbeitsblattes) am Bildschirm aus.    
II. Ermitteln Sie im Programm die Bezeichner der beiden Arbeitsblätter und geben Sie sie am
Bildschirm aus.    
III. Geben Sie die Daten des ersten Arbeitsblattes am Bildschirm aus, indem Sie beim
Methodenaufruf den Bezeichner dieses Arbeitsblattes verwenden. 

In [10]:
file='Wertemappen.xlsx' #Excel Datei wird einer Variable zugeweisen. Die Datei muss im selben Ordner liegen oder der Pfad muss angegeben werden.
data=pd.ExcelFile(file) #die Pandas Methode ExcelFile mit dem Argument der Variable der Datei, gibt das als Exceldatei aus und mann kann später auf die Arbeitsblätter zugreifen.
#I)
print(data.parse(0)) #die Parse Methode gibt durch den Index 0 das erste Arbeitsblatt aus.
#II)
print(data.sheet_names)#Das Attribut sheet_names gibt die Namen der Arbeitsblätter an der Konsole aus
#III)
print(data.parse('Werte'))# da wir nun den Namen der Arbeitsblätter kennen können wir statt den Index wie bei Aufgabe eins, den Namen als String in der parse Methode verwenden.


   Groesse   Gewicht   Systole
0      170        60       130
1      180        87       140
2      190        89       120
3      150        50       132
4      165        56       126
5      171        53       119
['Werte', 'WerteID', 'Tabelle1']
   Groesse   Gewicht   Systole
0      170        60       130
1      180        87       140
2      190        89       120
3      150        50       132
4      165        56       126
5      171        53       119


pandas.io.excel._base.ExcelFile