### Aufgabe 4 
a)

In [1]:

sysBlutdr = [] #diese Liste wird nach append in ein Array umgewandelt
sysBlutdr_Summe = 0
schleifendurchlauf = 0
import numpy as np #Numpy importiert unter Shortname np

while True:
    schleifendurchlauf = schleifendurchlauf + 1
    sysBlutdr_Wert = int(input("Systol. Blutdruckwert " + str(schleifendurchlauf) + ": "))
    sysBlutdr.append(sysBlutdr_Wert)
    weiter = input("Abbruch der Eingabe mit 'n' oder 'N', ansonsten z.B. 'Enter': ")
    if weiter == "N" or weiter == "n":
        break
np_sysblW=np.array(sysBlutdr) #array Funktion mit Parameter der Liste, verwandelt Liste in einen Array, speichert den unter dem Bezeichner: np_sysblW. Nach append, da die append Methode nicht für ein Array funktioniert.  
for element in np_sysblW: #Itariert das Array
    print(element)
    sysBlutdr_Summe += element
    
mw=np.mean(np_sysblW) #Mittelwerfunktion für Array. Berechnet den Mittelwert des Arrays. Argument der Funktion das Array
print("\nMittelwert der eingegebenen Blutdruckwerte: " + str(mw))

Systol. Blutdruckwert 1: 140
Abbruch der Eingabe mit 'n' oder 'N', ansonsten z.B. 'Enter': n
140

Mittelwert der eingegebenen Blutdruckwerte: 140.0


## b)


In [2]:

sysBlutdr_array=np.array([158,190,185,165,140]) #(Achtung Numpy schon importiert)Die Funktion np. array(Parameter= die Liste, die in ein Array umgewandelt werden soll.)
sysBlutdrVermindert_array=sysBlutdr_array-120 #skalare Subtraktion. 120 wird von jedem Element des Arrays abgezogen, das Ergebnis wird in dem neuen Array gespeichert(Bezeichner= sysBlutdrVermindert_array)
print("Ausgabe von Arrays OHNE Schleife:")
print(sysBlutdr_array) #Ausgabe des Array sysBlutdr
print(sysBlutdrVermindert_array) #Ausgabe der verminderten Werte

Ausgabe von Arrays OHNE Schleife:
[158 190 185 165 140]
[38 70 65 45 20]


## c)

In [3]:
print("Überprüfung auf Gleichheit, Substraktion:")
print(sysBlutdr_array==sysBlutdrVermindert_array+120) #Vergleichsoperator ==, vergleicht ob rechter und linker Ausdruck gleich sind. Bei dem verminderten Array wird durch skalare Addition 120 elementeweise addiert.Das Ergebnis ist ein boolscher Wert (TRUE)
print(sysBlutdr_array-sysBlutdrVermindert_array) #Die Differenz zwischen den Arrays wird berechnet. Die skalare Subtraktion. Elementeweise wird der Wert von einem Array von dem andern Array subtrahiert und das Ergebnis an der Konsole ausgegeben.

Überprüfung auf Gleichheit, Substraktion:
[ True  True  True  True  True]
[120 120 120 120 120]


## d)

In [4]:
print("Zugriffe und Zuweisung:")
print(sysBlutdr_array[1]) #Zugriff über Indizes. Der zweite Wert ist Index eins. Man beginnt bei Null zu zählen. Index ähnlich wie bei Listen in eckigen Klammern.

print(sysBlutdr_array[-1]) #Zugriff auf das letze Element. Wenn man von hinten zählt, immer mit -1 beginnend. -1 ist immer das letzte Element.

print(sysBlutdr_array[1:3]) #Slicing. Das zweite bis dritte Element werden ausgegebn. Erster Wert inklusiv, zweiter exklusiv. 

print(sysBlutdr_array[:3]) #Offener Anfang, alles bis zum dritten Element ausgeben. 3 wieder exklusiv

sysBlutdr_array[0]=125#Element mit Index 0 wird verändert. Bekommt einen neuen Wert zugewiesen.
print(sysBlutdr_array) #Array wird ausgegeben. Element mit Index 0 wurde verändert.

Zugriffe und Zuweisung:
190
140
[190 185]
[158 190 185]
[125 190 185 165 140]


## e)


In [5]:
print("Vergleiche / Filtern:")
print(sysBlutdr_array>150) 
#Vergleichsoperator geht alle Elemente des Arrays durch und vergleicht diese mit der Zahl 150, das Ergebnis des Vergleichsausdruck wird an der Konsole ausgegeben[False,True...]
print(sysBlutdr_array[sysBlutdr_array>150]) 
#Filtern. Wenn man den Vergleichsausdruck als Index notiert, werden einem nur die Werte ausgegeben die bei dem Vergleichsausdruck das Ergebnis True generiert haben.

Vergleiche / Filtern:
[False  True  True  True False]
[190 185 165]


## f)

In [6]:
print("Löschen:")
a=np.delete(sysBlutdr_array,1) #die delete Funktion löscht das Element, welches an der Stelle der Indexzahl hinter dem Array mit Komma getrennt steht. Dieses veränderte Array muss man unter einer Variable speichern. Da das original Array nicht verändert wird.
print(a)
print(sysBlutdr_array)#beim original Array wurde Element mit Index 1 nicht gelöscht.

Löschen:
[125 185 165 140]
[125 190 185 165 140]


## g)


In [7]:
erg=np.mean(sysBlutdr_array) #Funktion mean berechnet den Mittelwert des Arrays. Man muss erst den Shortname des Package nennen um auf die Funktion zugreifen zu können. Das wird mit Punktnotation aufgeschrieben.
print("Mittelwert der eingegebenen Blutdruckwerte per statist. Methode:",erg)

Mittelwert der eingegebenen Blutdruckwerte per statist. Methode: 161.0
